drop database if exists SISTEMA_GESTAO_IMOBILIARIA;
CREATE DATABASE SISTEMA_GESTAO_IMOBILIARIA;
USE SISTEMA_GESTAO_IMOBILIARIA;

CREATE TABLE TBL_ADM_IMOBILIARIA (
  ID_IMOBILIARIA INT NOT NULL AUTO_INCREMENT,
  ENDERECO VARCHAR(25) NULL,
  CNPJ VARCHAR(25) NULL,
  IE VARCHAR(25) NULL,
  PRIMARY KEY(ID_IMOBILIARIA)
  );
INSERT INTO `TBL_ADM_IMOBILIARIA` VALUES (default,'Rua Jose Alves','13.171.058/0001-40','388.158.598.269');
INSERT INTO `TBL_ADM_IMOBILIARIA` VALUES (default,'Rua Antonio Vilela','15.161.038/0001-40','389.108.598.269');
INSERT INTO `TBL_ADM_IMOBILIARIA` VALUES (default,'Rua Santo Amado','17.251.020/0001-40','388.132.598.269');

select * from TBL_ADM_IMOBILIARIA;

CREATE TABLE TBL_CLIENTE (
ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
  TBL_ADM_IMOBILIARIA_ID_IMOBILIARIA INT NOT NULL,
  TBL_IMOVEL_ID_IMOVEL INT NOT NULL,
  NOME_CLIENTE VARCHAR(25) NULL,
  ENDERECO VARCHAR(25) NULL,
  CPF VARCHAR(25) NULL,
  ID_IMOBILIARIA INT NULL,
  ID_IMOVEL INT NULL,
  PRIMARY KEY(ID_CLIENTE),
  INDEX TBL_CLIENTE_FKIndex1(TBL_IMOVEL_ID_IMOVEL),
  INDEX TBL_CLIENTE_FKIndex2(TBL_ADM_IMOBILIARIA_ID_IMOBILIARIA)
  
  );
  INSERT INTO `TBL_CLIENTE` VALUES (default,7453465,9345345,'Eduardo','Rua Joao da Fonseca','24589359874',6544451,4586987);
  INSERT INTO `TBL_CLIENTE` VALUES (default,8453465,5345345,'Joao','Rua Andrade','24589359874',6444451,4686987);
  INSERT INTO `TBL_CLIENTE` VALUES (default,9453465,6345345,'Diego','Rua Carlos Augusto ','34589359874',7544451,8586987);
  
  select * from TBL_CLIENTE;

 
CREATE TABLE TBL_IMOVEL (
  ID_IMOVEL INT NOT NULL AUTO_INCREMENT,
  TBL_PROPRIETARIO_ID_PROPRIETARIO INT NOT NULL,
  ENDERECO_IMOVEL VARCHAR(25) NULL,
  INSCRICAO_MUNICIPAL_IMOVEL VARCHAR(25) NULL,
  ID_PROPRIETARIO INT NULL,
  PRIMARY KEY(ID_IMOVEL),
  INDEX TBL_IMOVEL_FKIndex1(TBL_PROPRIETARIO_ID_PROPRIETARIO)
  );
  INSERT INTO `TBL_IMOVEL` VALUES (default,4598962,'Rua Alexandre Mattos','57845698',5258967);
  INSERT INTO `TBL_IMOVEL` VALUES (default,4588962,'Rua Lucas Lima','77845698',8258967); 
  INSERT INTO `TBL_IMOVEL` VALUES (default,4558962,'Rua Lucas Lee','97845698',2258967);
  
  select * from TBL_IMOVEL;
  
CREATE TABLE TBL_PROPRIETARIO (
  ID_PROPRIETARIO INT NOT NULL AUTO_INCREMENT,
  TBL_ADM_IMOBILIARIA_ID_IMOBILIARIA INT NOT NULL,
  ENDERECO VARCHAR(25) NULL,
  RG VARCHAR(25) NULL,
  CPD VARCHAR(25) NULL,
  ID_IMOBILIARIA INT NULL,
  PRIMARY KEY(ID_PROPRIETARIO),
  INDEX TBL_PROPRIETARIO_FKIndex1(TBL_ADM_IMOBILIARIA_ID_IMOBILIARIA)
  );
  INSERT INTO `TBL_PROPRIETARIO` VALUES (default,1479357,'Rua Andrade Alves','00000025487987-2','65456445',5879654);
  INSERT INTO `TBL_PROPRIETARIO` VALUES (default,2458796,'Rua Roberto Carlos','00000025487988-2','65456485',1257898);
  INSERT INTO `TBL_PROPRIETARIO` VALUES (default,8965447,'Rua Lucas Lima','00000025487997-2','65456478',4789541);
  
  select * from TBL_PROPRIETARIO;

SELECT * FROM TBL_ADM_IMOBILIARIA;
SELECT ID_IMOBILIARIA, ENDERECO FROM TBL_ADM_IMOBILIARIA WHERE CNPJ = '13.171.058/0001-40'; 
select * from TBL_ADM_IMOBILIARIA;

SELECT *
FROM TBL_ADM_IMOBILIARIA
WHERE CNPJ Like '%13.171.058/0001-40%';

CREATE VIEW VW_TBL_ADM_IMOBILIARIA
AS SELECT IE,ID_IMOBILIARIA,ENDERECO
FROM TBL_ADM_IMOBILIARIA;

SELECT * FROM VW_TBL_ADM_IMOBILIARIA;

SELECT * FROM VW_TBL_ADM_IMOBILIARIA LIMIT 3;

CREATE VIEW VW_TBL_ADM_IMOBILIARIA2
AS SELECT IE,ID_IMOBILIARIA,ENDERECO
FROM TBL_ADM_IMOBILIARIA;

SELECT * FROM VW_TBL_ADM_IMOBILIARIA2;

CREATE VIEW VW_TBL_ADM_IMOBILIARIA3
AS SELECT IE,ID_IMOBILIARIA,ENDERECO
FROM TBL_ADM_IMOBILIARIA;

SELECT * FROM VW_TBL_ADM_IMOBILIARIA3;

SELECT * FROM TBL_CLIENTE;
SELECT TBL_ADM_IMOBILIARIA_ID_IMOBILIARIA, TBL_IMOVEL_ID_IMOVEL FROM TBL_CLIENTE WHERE NOME_CLIENTE = 'Eduardo'; 
select * from TBL_CLIENTE;

SELECT *
FROM TBL_CLIENTE
WHERE NOME_CLIENTE Like '%Eduardo%';

CREATE VIEW VW_TBL_CLIENTE
AS SELECT ENDERECO,TBL_ADM_IMOBILIARIA_ID_IMOBILIARIA,TBL_IMOVEL_ID_IMOVEL
FROM TBL_CLIENTE;

SELECT * FROM VW_TBL_CLIENTE;

SELECT * FROM VW_TBL_CLIENTE LIMIT 3;

CREATE VIEW VW_TBL_CLIENTE2
AS SELECT ENDERECO,TBL_ADM_IMOBILIARIA_ID_IMOBILIARIA,TBL_IMOVEL_ID_IMOVEL
FROM TBL_CLIENTE;

SELECT * FROM VW_TBL_CLIENTE2;

CREATE VIEW VW_TBL_CLIENTE3
AS SELECT ENDERECO,TBL_ADM_IMOBILIARIA_ID_IMOBILIARIA,TBL_IMOVEL_ID_IMOVEL
FROM TBL_CLIENTE;

SELECT * FROM VW_TBL_CLIENTE3;

SELECT * FROM TBL_IMOVEL;
SELECT TBL_PROPRIETARIO_ID_PROPRIETARIO, ENDERECO_IMOVEL FROM TBL_IMOVEL WHERE INSCRICAO_MUNICIPAL_IMOVEL = '57845698'; 
select * from TBL_IMOVEL;

SELECT *
FROM TBL_IMOVEL
WHERE INSCRICAO_MUNICIPAL_IMOVEL Like '%57845698%';

CREATE VIEW VW_TBL_IMOVEL
AS SELECT ID_PROPRIETARIO,TBL_PROPRIETARIO_ID_PROPRIETARIO,ENDERECO_IMOVEL
FROM TBL_IMOVEL;

SELECT * FROM VW_TBL_IMOVEL;

SELECT * FROM VW_TBL_IMOVEL LIMIT 3;

CREATE VIEW VW_TBL_IMOVEL2
AS SELECT ID_PROPRIETARIO,TBL_PROPRIETARIO_ID_PROPRIETARIO,ENDERECO_IMOVEL
FROM TBL_IMOVEL;

SELECT * FROM VW_TBL_IMOVEL2;

CREATE VIEW VW_TBL_IMOVEL3
AS SELECT ID_PROPRIETARIO,TBL_PROPRIETARIO_ID_PROPRIETARIO,ENDERECO_IMOVEL
FROM TBL_IMOVEL;

SELECT * FROM VW_TBL_IMOVEL3;

SELECT * FROM TBL_PROPRIETARIO;
SELECT TBL_ADM_IMOBILIARIA_ID_IMOBILIARIA, ENDERECO FROM TBL_PROPRIETARIO WHERE RG = '00000025487987-2'; 
select * from TBL_PROPRIETARIO;

SELECT *
FROM TBL_PROPRIETARIO
WHERE RG Like '%00000025487987-2%';

CREATE VIEW VW_TBL_PROPRIETARIO
AS SELECT CPD,TBL_ADM_IMOBILIARIA_ID_IMOBILIARIA,ENDERECO
FROM TBL_PROPRIETARIO;

SELECT * FROM VW_TBL_PROPRIETARIO;

SELECT * FROM VW_TBL_PROPRIETARIO LIMIT 3;

CREATE VIEW VW_TBL_PROPRIETARIO2
AS SELECT CPD,TBL_ADM_IMOBILIARIA_ID_IMOBILIARIA,ENDERECO
FROM TBL_PROPRIETARIO;

SELECT * FROM VW_TBL_PROPRIETARIO2;

CREATE VIEW VW_TBL_PROPRIETARIO3
AS SELECT CPD,TBL_ADM_IMOBILIARIA_ID_IMOBILIARIA,ENDERECO
FROM TBL_PROPRIETARIO;

SELECT * FROM VW_TBL_PROPRIETARIO3;

SELECT TBL_ADM_IMOBILIARIA. ID_IMOBILIARIA, TBL_CLIENTE.Nome_CLIENTE
FROM TBL_ADM_IMOBILIARIA, TBL_CLIENTE
WHERE TBL_ADM_IMOBILIARIA. ID_IMOBILIARIA = TBL_CLIENTE. ID_IMOBILIARIA AND XXXX > 50.00


